//
// Body1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body1: Codable {

    public var title: String?
    public var dueBy: Int?
    public var priority: Priority?

    public init(title: String?, dueBy: Int?, priority: Priority?) {
        self.title = title
        self.dueBy = dueBy
        self.priority = priority
    }


}

