//
// InlineResponse201.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse201: Codable {

    public var task: TaskPresenter?

    public init(task: TaskPresenter?) {
        self.task = task
    }


}

