//
// InlineResponse200Meta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200Meta: Codable {

    /** a current page number */
    public var current: Int?
    /** maximum amount of items per page */
    public var limit: Int?
    /** amount of items by criteria */
    public var count: Int?

    public init(current: Int?, limit: Int?, count: Int?) {
        self.current = current
        self.limit = limit
        self.count = count
    }


}

