//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var tasks: [TaskPresenter]?
    public var meta: InlineResponse200Meta?

    public init(tasks: [TaskPresenter]?, meta: InlineResponse200Meta?) {
        self.tasks = tasks
        self.meta = meta
    }


}

