//
// InlineResponse4221Fields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse4221Fields: Codable {

    public var email: [String]?

    public init(email: [String]?) {
        self.email = email
    }


}

