//
// InlineResponse4221.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse4221: Codable {

    public var message: String?
    public var fields: InlineResponse4221Fields?

    public init(message: String?, fields: InlineResponse4221Fields?) {
        self.message = message
        self.fields = fields
    }


}

