//
// InlineResponse422.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse422: Codable {

    public var message: String?
    public var fields: String?

    public init(message: String?, fields: String?) {
        self.message = message
        self.fields = fields
    }


}

