//
// Priority.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum Priority: String, Codable {
    case low = "Low"
    case normal = "Normal"
    case high = "High"
}