//
// TaskPresenter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TaskPresenter: Codable {

    public var _id: Int?
    public var title: String?
    public var dueBy: Int?
    public var priority: String?

    public init(_id: Int?, title: String?, dueBy: Int?, priority: String?) {
        self._id = _id
        self.title = title
        self.dueBy = dueBy
        self.priority = priority
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case dueBy
        case priority
    }

}

